server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:h2:file:./data
  devtools:
    livereload:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
